export const PARTNERS = [
  {
    id: 'stable_money',
    name: 'Stable Money',
    logo: '🏦',
    rates: { '1yr': 7.50, '2yr': 7.75, '3yr': 8.00 },
    affiliateUrl: 'https://stablemoney.in?ref=audkit',
    commission: '₹750 flat per booking',
    dicgcInsured: true,
    maxDeposit: 500000,
    badge: 'Most Popular',
  },
  {
    id: 'grip_invest',
    name: 'Grip Invest',
    logo: '📊',
    rates: { '1yr': 7.80, '2yr': 8.10, '3yr': 8.25 },
    affiliateUrl: 'https://gripinvest.in?ref=audkit',
    commission: '₹800 flat per booking',
    dicgcInsured: true,
    maxDeposit: 500000,
    badge: null,
  },
  {
    id: 'idfc_first',
    name: 'IDFC First Bank',
    logo: '🏛',
    rates: { '1yr': 7.25, '2yr': 7.50, '3yr': 7.75 },
    affiliateUrl: 'https://idfcfirstbank.com?ref=audkit',
    commission: '₹600 flat per booking',
    dicgcInsured: true,
    maxDeposit: 500000,
    badge: null,
  },
  {
    id: 'equitas_sfb',
    name: 'Equitas SFB',
    logo: '🌟',
    rates: { '1yr': 8.00, '2yr': 8.25, '3yr': 8.50 },
    affiliateUrl: 'https://equitasbank.com?ref=audkit',
    commission: '₹900 flat per booking',
    dicgcInsured: true,
    maxDeposit: 500000,
    badge: 'Highest Rate',
  },
  {
    id: 'au_sfb',
    name: 'AU Small Finance',
    logo: '💰',
    rates: { '1yr': 7.60, '2yr': 7.90, '3yr': 8.10 },
    affiliateUrl: 'https://aubank.in?ref=audkit',
    commission: '₹700 flat per booking',
    dicgcInsured: true,
    maxDeposit: 500000,
    badge: null,
  },
];
